safe: true
lsi: false
pygments: true

encoding: utf-8

timezone: Japan/Tokyo
name: egy186's Blog
author: egy186
twitter_account: egp186
twitter_data-widget-id: 311496198525685762
ga_tracking_id: UA-41929002-1